CMR-5199 Adds request-id to result map.
cmr-exchange/cmr-exchange-common pull request #3
Opened 2018-11-14 18:49 UTC by daniel-zamora

2018-11-15 15:25 UTC, oubiwann approved these changes

2018-11-15 15:25 UTC, oubiwann commented on src/cmr/exchange/common/results/core.clj
> +            :request-id request-id
Good job on the `request-id` ... better than what we'd talked about before (`id`) giving more specificity in the context of Splunk queries, etc.

2018-11-15 15:37 UTC, chris-durbin approved these changes

2018-11-15 16:02 UTC, oubiwann requested changes
Oh, wait! You need to also bump the micro-version (for Nexus ...)

2018-11-16 16:14 UTC, oubiwann commented
Pairing with Daniel on this now ...

2018-11-16 16:14 UTC, oubiwann approved these changes

2018-11-16 16:18 UTC, merged